### PR TITLE
use title instead of name

### PR DESCRIPTION
**Pull request by dropmann**

### CODE REVIEW

**Comment by jonathon-love** [comment]
Hey, what's the rationale for this?
Doesn't it break everything?

**Comment by dropmann** [comment]
why does it break everything? Why would title not be better than name? Does title not always exist?



damo


On Nov 11, 2016, at 09:58 AM, Jonathon Love <notifications@github.com> wrote:



Hey, what's the rationale for this?
Doesn't it break everything?

**Comment by jonathon-love** [comment]
Aren't you requiring a file which is never created? I.e. the compiler is generating ttestis.options.js, and this will try and require 'Independent Samples T-Test.options.js'

But the idea of the name is that that's what is used under the hood. They're unique (within a module), and they're plain ASCII, so they don't causes issues with filesystems, etc.

Where as two analyses might have the title 'independent samples' for example, but come under different subheadings.

Anyhow, those are the sorts of rationale for separating name and title.

**Comment by jonathon-love** [comment]
It also makes all the files consistent. They're all ttestis.something

**Comment by dropmann** [comment]
ah shit, sorry jLo, your emails have made no sense, so i went back and looked at what i did. My mistake i modified the wrong line. Ignore that commit and i'll commit another after a reset.



damo




On Nov 11, 2016, at 11:26 AM, Jonathon Love <notifications@github.com> wrote:



It also makes all the files consistent. They're all ttestis.something

**Comment by dropmann** [comment]
sorry it's been committed properly now.



damo


On Nov 11, 2016, at 11:26 AM, Jonathon Love <notifications@github.com> wrote:



It also makes all the files consistent. They're all ttestis.something

**Pull request closed without merging**
